# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
version: 1
language: tr

reviews:
  auto_review: true
  summary: true
  inline_comments: true

  tools:
    htmlhint:
      enabled: true
    biome:
      enabled: true
    eslint:
      enabled: true
    markdownlint:
      enabled: true

  path_instructions:
    - path: "**/*.html"
      instructions: "WCAG 2.2 AA: keyboard/focus order, labels, alt; SEO: title/meta/rel=canonical; avoid multiple H1; async/defer scripts; avoid layout shift."
    - path: "**/*.js"
      instructions: "Null-safe DOM queries; handle promise rejections; debounce scroll/resize; resilient mobile menu toggles."
    - path: "**/*.css"
      instructions: "Responsive breakpoints; prefers-reduced-motion; min contrast 4.5:1; reduce unused CSS; avoid !important."

  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!**/*.min.js"
    - "!**/*.map"
